WIDTH  = 800
HEIGHT = 400
FPS    = 60
SKY_IMAGE_HEIGHT    = 300
PLAYER_IMAGE_WIDTH  = 64
PLAYER_IMAGE_HEIGHT = 84
SNAIL_IMAGE_HEIGHT  = 36
SNAIL_IMAGE_WIDTH   = 72
FLY_IMAGE_HEIGHT    = 40
FLY_IMAGE_WIDTH     = 84
FONT_SIZE = 40
# Y_Level
# Game screen
SCORE_Y      = 20
SKY_LEVEL    = 0
GROUND_LEVEL = SKY_LEVEL + SKY_IMAGE_HEIGHT
FLY_Y        = GROUND_LEVEL - PLAYER_IMAGE_HEIGHT - 20
SNAIL_Y      = GROUND_LEVEL
# End game
NAME_Y         = 10
INSTRUCTION_Y  = HEIGHT - 10
FINAL_SCORE_Y  = INSTRUCTION_Y - FONT_SIZE
PLAYER_STAND_Y = FINAL_SCORE_Y - FONT_SIZE - 30
# COLOR
TEXT_COLOR               = (64,64,64)
ENDGAME_TEXT_COLOR       = (111,196,169)
ENDGAME_BACKGROUND_COLOR = (94,129,162)
# ANIMATION
PLAYER_ANIMATION_SPEED = 4
ENEMY_ANIMATION_SPEED  = 5 
# STATS
ENEMY_SPEED  = 300
GRAVITY_JUMP = -20
GRAVITY      = 1
# TIMERS
SPAWNING_SPEED = 1500 # in milliseconds