<<<<<<< HEAD
WINDOW_WIDTH  = 600
WINDOW_HEIGHT = 720
BACKGROUND_COLOR = "black"
FPS = 120

BACKGROUND_IMAGE_HEIGHT = 480
BACKGROUND_IMAGE_WIDTH  = 800
SCALE_FACTOR = WINDOW_HEIGHT/BACKGROUND_IMAGE_HEIGHT
OBSTACLE_SCALE_FACTOR = SCALE_FACTOR*1.2

GRAVIY       = 600
JUMP_GRAVITY = -300

BACKGROUND_ANIMATION_SPEED = 200
GROUND_ANIMATION_SPEED     = 250
OBSTACLE_ANIMATION_SPEED   = 300
PLANE_ANIMATION_SPEED      = 20
PLANE_ROTATION_SPEED       = 0.09
OBSTACLE_SPAWNING_SPEED    = 1500 # in milliseconds

FONT_SIZE   = 40
SCORE_COLOR = "black"
=======
WINDOW_WIDTH  = 600
WINDOW_HEIGHT = 720
BACKGROUND_COLOR = "black"
FPS = 120

BACKGROUND_IMAGE_HEIGHT = 480
BACKGROUND_IMAGE_WIDTH  = 800
SCALE_FACTOR = WINDOW_HEIGHT/BACKGROUND_IMAGE_HEIGHT
OBSTACLE_SCALE_FACTOR = SCALE_FACTOR*1.2

GRAVIY       = 600
JUMP_GRAVITY = -300

BACKGROUND_ANIMATION_SPEED = 200
GROUND_ANIMATION_SPEED     = 250
OBSTACLE_ANIMATION_SPEED   = 300
PLANE_ANIMATION_SPEED      = 20
PLANE_ROTATION_SPEED       = 0.09
OBSTACLE_SPAWNING_SPEED    = 1500 # in milliseconds

FONT_SIZE   = 40
SCORE_COLOR = "black"
>>>>>>> b5d4c06fe06fac9355bddf6676ca7acd835b2e79
JUMP_VOLUME = 0.3